name: letsshop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  app_settings: ^6.1.1
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  # flutter_keyboard_visibility: ^6.0.0
  flutter_easyloading: ^3.0.5
  flutter_local_notifications: ^19.4.1
  flutter_rating_bar: ^4.0.1
  flutter_swipe_action_cell: ^3.1.5
  get: ^4.7.2
  google_sign_in: ^6.2.1
  googleapis_auth: ^2.0.0
  http: ^1.5.0
  image_card: ^0.0.4
  keyboard_avoider: ^0.2.0
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - lib/assets/images/splash_screen.json
    - lib/assets/images/google-logo.png
  
