// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd_c0fo3y4TyOOmhQuC3UdglEitdRMsrg',
    appId: '1:1060523916231:web:7e88f798de474b1abbf7e2',
    messagingSenderId: '1060523916231',
    projectId: 'let-s-shop-47c2a',
    authDomain: 'let-s-shop-47c2a.firebaseapp.com',
    storageBucket: 'let-s-shop-47c2a.firebasestorage.app',
    measurementId: 'G-8MBD65B871',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4dn3gkS5wd40So7OpDicyKqoLSVC4Vz8',
    appId: '1:1060523916231:android:890f1dae572e4cdebbf7e2',
    messagingSenderId: '1060523916231',
    projectId: 'let-s-shop-47c2a',
    storageBucket: 'let-s-shop-47c2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz7oKSCe8vWmXaCpWo_ZF1gd5KQh4RuCQ',
    appId: '1:1060523916231:ios:a136fea37a3362a0bbf7e2',
    messagingSenderId: '1060523916231',
    projectId: 'let-s-shop-47c2a',
    storageBucket: 'let-s-shop-47c2a.firebasestorage.app',
    iosBundleId: 'com.example.letsshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz7oKSCe8vWmXaCpWo_ZF1gd5KQh4RuCQ',
    appId: '1:1060523916231:ios:a136fea37a3362a0bbf7e2',
    messagingSenderId: '1060523916231',
    projectId: 'let-s-shop-47c2a',
    storageBucket: 'let-s-shop-47c2a.firebasestorage.app',
    iosBundleId: 'com.example.letsshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd_c0fo3y4TyOOmhQuC3UdglEitdRMsrg',
    appId: '1:1060523916231:web:23874cd12424d941bbf7e2',
    messagingSenderId: '1060523916231',
    projectId: 'let-s-shop-47c2a',
    authDomain: 'let-s-shop-47c2a.firebaseapp.com',
    storageBucket: 'let-s-shop-47c2a.firebasestorage.app',
    measurementId: 'G-V2NJK5V7GD',
  );
}
